version: '3.4'

services:
  2fademo:
    image: ${DOCKER_REGISTRY-}2fademo
    build:
      context: .
      dockerfile: 2FA Demo/Dockerfile
  mysql:
    container_name: mysql
    ports: 
        - "3306:3306"
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    volumes:
    - ./data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'